name: Deploy AI Meeting Assistant

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      WEBHOOK_AUTH_TOKEN: ${{ secrets.WEBHOOK_AUTH_TOKEN }}
      ZOOM_JWT: ${{ secrets.ZOOM_JWT }}
      TEAMS_API_TOKEN: ${{ secrets.TEAMS_API_TOKEN }}
      APP_USERNAME: ${{ secrets.APP_USERNAME }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y ffmpeg libsndfile1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI server (test only)
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 10
        curl --fail http://localhost:8000 || exit 1
